// Generated from src/queries/*.graphql. Do not edit by hand.
import { parse, print } from "graphql";

const persistedSources = {
  "Badges": "query Badges(\n  $first: Int!\n  $skip: Int!\n  $orderBy: Badge_orderBy!\n  $orderDirection: OrderDirection!\n  $where: Badge_filter\n) {\n  badges(\n    first: $first\n    skip: $skip\n    orderBy: $orderBy\n    orderDirection: $orderDirection\n    where: $where\n  ) {\n    id\n    name\n    description\n    isOfficial\n    isCommunity\n    uri\n    imageUrl\n    creatorAddress\n    profileUser {\n      name\n    }\n    community {\n      id\n      name\n    }\n    createdBy {\n      id\n      name\n      bio\n      imageUrl\n    }\n  }\n}\n",
  "Badge": "query Badge($id: ID!) {\n  badge(id: $id) {\n    id\n    name\n    description\n    isOfficial\n    isCommunity\n    uri\n    hookAddress\n    imageUrl\n    creatorAddress\n    createdAt\n    holdersCount\n    profileUser {\n      name\n    }\n    community {\n      id\n      name\n    }\n    holders {\n      id\n      name\n      bio\n      imageUrl\n    }\n    managers {\n      id\n      name\n      bio\n      imageUrl\n    }\n    minters {\n      id\n      name\n      profileUser {\n        name\n      }\n      holders {\n        id\n      }\n    }\n    burners {\n      id\n      name\n      profileUser {\n        name\n      }\n      holders {\n        id\n      }\n    }\n    transferers {\n      id\n      name\n      profileUser {\n        name\n      }\n      holders {\n        id\n      }\n    }\n  }\n}\n",
  "User": "query User($id: ID!) {\n  user(id: $id) {\n    id\n    name\n    bio\n    imageUrl\n    communities(first: 1000) {\n      id\n    }\n    profile {\n      id\n    }\n    invitedBy {\n      id\n      name\n      bio\n      imageUrl\n    }\n    badges(first: 1000, where: { isProfile: false }) {\n      id\n      name\n      description\n      isOfficial\n      isCommunity\n      uri\n      hookAddress\n      imageUrl\n      creatorAddress\n      createdAt\n      holdersCount\n      community {\n        id\n        name\n      }\n      createdBy {\n        id\n        name\n        bio\n        imageUrl\n      }\n    }\n    managedBadges(first: 1000, where: { isProfile: false }) {\n      id\n      name\n      description\n      isOfficial\n      isCommunity\n      uri\n      hookAddress\n      imageUrl\n      creatorAddress\n      createdAt\n      holdersCount\n      createdBy {\n        id\n        name\n        bio\n        imageUrl\n      }\n    }\n  }\n}\n",
  "Users": "query Users(\n  $first: Int!\n  $skip: Int!\n  $orderBy: User_orderBy!\n  $orderDirection: OrderDirection!\n  $where: User_filter\n) {\n  users(\n    first: $first\n    skip: $skip\n    orderBy: $orderBy\n    orderDirection: $orderDirection\n    where: $where\n  ) {\n    id\n    name\n    bio\n    imageUrl\n    profile {\n      id\n    }\n  }\n}\n",
  "Status": "query Status {\n  _meta {\n    block {\n      number\n    }\n  }\n}\n",
  "Auction": "query Auction($id: ID!) {\n  auctionDetail(id: $id) {\n    id\n    auctionId\n    chainId\n    symbolAuctioningToken\n    symbolBiddingToken\n    addressAuctioningToken\n    addressBiddingToken\n    decimalsAuctioningToken\n    decimalsBiddingToken\n    endTimeTimestamp\n    orderCancellationEndDate\n    startingTimeStamp\n    minimumBiddingAmountPerOrder\n    minFundingThreshold\n    allowListManager\n    allowListSigner\n    currentVolume\n    currentClearingOrderSellAmount\n    currentClearingOrderBuyAmount\n    currentClearingPrice\n    currentBiddingAmount\n    isAtomicClosureAllowed\n    isPrivateAuction\n    interestScore\n    usdAmountTraded\n\n    exactOrder {\n      id\n      sellAmount\n      buyAmount\n      userAddress\n      price\n      volume\n      timestamp\n    }\n\n    orders {\n      id\n      sellAmount\n      buyAmount\n      userAddress\n      price\n      volume\n      timestamp\n    }\n  }\n}\n",
  "Orders": "query Orders($auctionId: BigInt!, $user: String!) {\n  orders(where: { auctionId: $auctionId, auctionUser_: { user: $user } }) {\n    id\n    sellAmount\n    buyAmount\n    userAddress\n    price\n    volume\n    timestamp\n  }\n}\n",
  "AuctionStatus": "query AuctionStatus($id: ID!) {\n  auctionDetail(id: $id) {\n    id\n    auctionId\n    chainId\n    endTimeTimestamp\n  }\n}\n",
  "LockTransactions": "query LockTransactions($user: Bytes!) {\n  lockTransactions(\n    where: { userAddress: $user }\n    orderBy: lockDate\n    orderDirection: desc\n  ) {\n    id\n    amount\n    lockDate\n    unlockDate\n    type\n  }\n}\n",
  "Communities": "query Communities(\n  $first: Int!\n  $skip: Int!\n  $orderBy: Community_orderBy!\n  $orderDirection: OrderDirection!\n  $where: Community_filter\n) {\n  communities(\n    first: $first\n    skip: $skip\n    orderBy: $orderBy\n    orderDirection: $orderDirection\n    where: $where\n  ) {\n    id\n    name\n    description\n    imageUrl\n    createdAt\n    tierId\n    tierName\n    tierExpiresAt\n    managerAddress\n    manager {\n      id\n      name\n      bio\n      imageUrl\n    }\n    memberCount\n  }\n}\n",
  "Community": "query Community($id: ID!) {\n  community(id: $id) {\n    id\n    name\n    description\n    imageUrl\n    createdAt\n    tierId\n    tierName\n    tierExpiresAt\n    managerAddress\n    manager {\n      id\n      name\n      bio\n      imageUrl\n    }\n    managerBadge {\n      id\n      name\n      imageUrl\n      uri\n    }\n    assistantBadge {\n      id\n      name\n      imageUrl\n      uri\n    }\n    memberBadge {\n      id\n      name\n      imageUrl\n      uri\n    }\n    memberCount\n    badges(first: 1000) {\n      id\n      name\n      imageUrl\n      isOfficial\n      isCommunity\n      holdersCount\n    }\n  }\n}\n",
  "CommunityMembers": "query CommunityMembers(\n  $first: Int\n  $skip: Int\n  $where: CommunityMembership_filter\n  $orderBy: CommunityMembership_orderBy\n  $orderDirection: OrderDirection\n) {\n  communityMemberships(\n    first: $first\n    skip: $skip\n    orderBy: $orderBy\n    orderDirection: $orderDirection\n    where: $where\n  ) {\n    id\n    joinActivity {\n      id\n      timestamp\n    }\n    user {\n      id\n      name\n      bio\n      imageUrl\n    }\n  }\n}\n",
  "CommunityActivities": "query CommunityActivities($communityId: String!, $first: Int!, $skip: Int!) {\n  communityActivityEvents(\n    where: { community: $communityId }\n    orderBy: timestamp\n    orderDirection: desc\n    first: $first\n    skip: $skip\n  ) {\n    __typename\n    id\n    timestamp\n    txHash\n    ... on MemberJoinedActivity {\n      user {\n        id\n        name\n        imageUrl\n      }\n    }\n    ... on MemberLeftActivity {\n      user {\n        id\n        name\n        imageUrl\n      }\n    }\n    ... on BadgeMintedActivity {\n      badge {\n        id\n        name\n      }\n      user {\n        id\n        name\n        imageUrl\n      }\n    }\n    ... on MemberTransferredActivity {\n      fromUser {\n        id\n        name\n        imageUrl\n      }\n      toUser {\n        id\n        name\n        imageUrl\n      }\n    }\n    ... on ManagerChangedActivity {\n      fromManager {\n        id\n        name\n        imageUrl\n      }\n      toManager {\n        id\n        name\n        imageUrl\n      }\n    }\n    ... on CommunityBadgeLinkedActivity {\n      badge {\n        id\n        name\n      }\n    }\n    ... on BadgeBurnedActivity {\n      badge {\n        id\n        name\n      }\n      user {\n        id\n        name\n        imageUrl\n      }\n    }\n    ... on CommunityTierGrantedActivity {\n      tierId\n      tierName\n      tierExpiresAt\n    }\n    ... on CommunityTierRevokedActivity {\n      previousTierId\n      previousTierName\n    }\n  }\n}\n"
} as const;

export const PERSISTED_GRAPH_DOCUMENTS = new Map<string, string>(
  Object.entries(persistedSources).map(([name, source]) => [
    name,
    print(parse(source)),
  ]),
);
