sources:
  - name: society-subgraph
    handler:
      graphql:
        endpoint: ${NEXT_PUBLIC_GRAPH_URL}
documents:
  - ./src/queries/badges.graphql
  - ./src/queries/badge.graphql
  - ./src/queries/user.graphql
  - ./src/queries/users.graphql
  - ./src/queries/status.graphql
  - ./src/queries/auction.graphql
  - ./src/queries/orders.graphql
  - ./src/queries/auctionStatus.graphql
  - ./src/queries/lockTransactions.graphql
  - ./src/queries/communities.graphql
  - ./src/queries/community.graphql
  - ./src/queries/communityActivities.graphql
