query Auction($id: ID!) {
  auctionDetail(id: $id) {
    id
    auctionId
    chainId
    symbolAuctioningToken
    symbolBiddingToken
    addressAuctioningToken
    addressBiddingToken
    decimalsAuctioningToken
    decimalsBiddingToken
    endTimeTimestamp
    orderCancellationEndDate
    startingTimeStamp
    minimumBiddingAmountPerOrder
    minFundingThreshold
    allowListManager
    allowListSigner
    currentVolume
    currentClearingOrderSellAmount
    currentClearingOrderBuyAmount
    currentClearingPrice
    currentBiddingAmount
    isAtomicClosureAllowed
    isPrivateAuction
    interestScore
    usdAmountTraded

    exactOrder {
      id
      sellAmount
      buyAmount
      userAddress
      price
      volume
      timestamp
      auctionUser {
        id
        address
        user {
          id
          name
          bio
          imageUrl
        }
      }
    }

    orders {
      id
      sellAmount
      buyAmount
      userAddress
      price
      volume
      timestamp
      auctionUser {
        id
        address
        user {
          id
          name
          bio
          imageUrl
        }
      }
    }

    ordersWithoutClaimed {
      id
      sellAmount
      buyAmount
      userAddress
      price
      volume
      timestamp
      auctionUser {
        id
        address
        user {
          id
          name
          bio
          imageUrl
        }
      }
    }
  }
}
