query Badges(
  $first: Int!
  $skip: Int!
  $orderBy: Badge_orderBy!
  $orderDirection: OrderDirection!
  $where: Badge_filter
) {
  badges(
    first: $first
    skip: $skip
    orderBy: $orderBy
    orderDirection: $orderDirection
    where: $where
  ) {
    id
    name
    description
    isOfficial
    isCommunity
    uri
    imageUrl
    metadata {
      description
      imageUrl
    }
    creatorAddress
    profileUser {
      name
      metadata {
        name
      }
    }
    community {
      id
      name
    }
    createdBy {
      id
      name
      bio
      imageUrl
      metadata {
        name
        bio
        imageUrl
      }
    }
  }
}
