query Community($id: ID!) {
  community(id: $id) {
    id
    name
    description
    imageUrl
    metadata {
      imageUrl
      description
    }
    createdAt
    tierId
    tierName
    tierExpiresAt
    managerAddress
    manager {
      id
      name
      bio
      imageUrl
      metadata {
        name
        bio
        imageUrl
      }
    }
    managerBadge {
      id
      name
      imageUrl
      uri
      metadata {
        imageUrl
      }
    }
    assistantBadge {
      id
      name
      imageUrl
      uri
      metadata {
        imageUrl
      }
    }
    memberBadge {
      id
      name
      imageUrl
      uri
      metadata {
        imageUrl
      }
    }
    memberCount
    badges(first: 1000) {
      id
      name
      imageUrl
      metadata {
        imageUrl
      }
      isOfficial
      isCommunity
      holdersCount
    }
  }
}
