query Users(
  $first: Int!
  $skip: Int!
  $orderBy: User_orderBy!
  $orderDirection: OrderDirection!
  $where: User_filter
) {
  users(
    first: $first
    skip: $skip
    orderBy: $orderBy
    orderDirection: $orderDirection
    where: $where
  ) {
    id
    name
    bio
    imageUrl
    badges {
      id
      name
      isOfficial
      isCommunity
      uri
      hookAddress
      imageUrl
      creatorAddress
      createdAt
      holdersCount
      createdBy {
        id
        name
        bio
        imageUrl
      }
      holders {
        id
        name
        bio
        imageUrl
      }
      managers {
        id
        name
        bio
        imageUrl
      }
      minters {
        id
        name
        holders {
          id
        }
      }
      burners {
        id
        name
        holders {
          id
        }
      }
      transferers {
        id
        name
        holders {
          id
        }
      }
    }
    managedBadges {
      id
      name
      isOfficial
      isCommunity
      uri
      hookAddress
      imageUrl
      creatorAddress
      createdAt
      holdersCount
      createdBy {
        id
        name
        bio
        imageUrl
      }
      holders {
        id
        name
        bio
        imageUrl
      }
      managers {
        id
        name
        bio
        imageUrl
      }
      minters {
        id
        name
        holders {
          id
        }
      }
      burners {
        id
        name
        holders {
          id
        }
      }
      transferers {
        id
        name
        holders {
          id
        }
      }
    }
  }
}
