query User($id: ID!) {
  user(id: $id) {
    id
    name
    bio
    imageUrl
    metadata {
      name
      bio
      imageUrl
    }
    communities(first: 1000) {
      id
    }
    profile {
      id
    }
    invitedBy {
      id
      name
      bio
      imageUrl
      metadata {
        name
        bio
        imageUrl
      }
    }
    badges(first: 1000, where: { isProfile: false }) {
      id
      name
      description
      isOfficial
      isCommunity
      uri
      hookAddress
      imageUrl
      metadata {
        description
        imageUrl
      }
      creatorAddress
      createdAt
      holdersCount
      community {
        id
        name
      }
      createdBy {
        id
        name
        bio
        imageUrl
        metadata {
          name
          bio
          imageUrl
        }
      }
    }
    managedBadges(first: 1000, where: { isProfile: false }) {
      id
      name
      description
      isOfficial
      isCommunity
      uri
      hookAddress
      imageUrl
      metadata {
        description
        imageUrl
      }
      creatorAddress
      createdAt
      holdersCount
      createdBy {
        id
        name
        bio
        imageUrl
        metadata {
          name
          bio
          imageUrl
        }
      }
    }
  }
}
